export * from './signup.interface'
export * from './modal.interface'
export * from './notification.interface'
export * from './error.interface'
export * from './login.interface'
export * from "./response.interface"
export * from "./user.interface"
export * from "./route.interface"
export * from "./message.interface"
export * from "./confirm.interface"